// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GenerateRoomTypesData, GenerateRoomTypesError, GenerateBubblesData, GenerateBubblesError, GenerateBubblesOldData, GenerateBubblesOldError, GenerateBubblesNewData, GenerateBubblesNewError, HealthData } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Generate Room Types
 */
export const generateRoomTypes = <ThrowOnError extends boolean = false>(options: Options<GenerateRoomTypesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, GenerateRoomTypesError, ThrowOnError>({
        url: '/generate/room_types',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Generate Bubbles
 */
export const generateBubbles = <ThrowOnError extends boolean = false>(options: Options<GenerateBubblesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, GenerateBubblesError, ThrowOnError>({
        url: '/generate/bubbles',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Generate Bubbles Old
 */
export const generateBubblesOld = <ThrowOnError extends boolean = false>(options: Options<GenerateBubblesOldData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, GenerateBubblesOldError, ThrowOnError>({
        url: '/generate/bubbles_old',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Generate Bubbles New
 */
export const generateBubblesNew = <ThrowOnError extends boolean = false>(options: Options<GenerateBubblesNewData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, GenerateBubblesNewError, ThrowOnError>({
        url: '/generate/bubbles_new',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};