// This file is auto-generated by @hey-api/openapi-ts

export type BubblesInputParameters = {
    condition_scale?: number;
    rescaled_phi?: number;
    num_samples?: number;
    num_steps?: number;
    ddim?: boolean;
    mask: Array<Array<Array<number>>>;
    as_image?: boolean;
    bubbles?: Array<Array<Array<number>>> | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type RoomTypeInputParameters = {
    condition_scale?: number;
    rescaled_phi?: number;
    num_samples?: number;
    num_steps?: number;
    ddim?: boolean;
    mask: Array<Array<Array<number>>>;
    as_image?: boolean;
    room_types?: Array<number> | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type BaseInputParameters = {
    condition_scale?: number;
    rescaled_phi?: number;
    num_samples?: number;
    num_steps?: number;
    ddim?: boolean;
    mask: Array<Array<Array<number>>>;
    as_image?: boolean;
};

export type GenerateBubblesData = {
    body: BubblesInputParameters;
    path?: never;
    query?: never;
    url: '/generate/bubbles';
};

export type GenerateBubblesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateBubblesError = GenerateBubblesErrors[keyof GenerateBubblesErrors];

export type GenerateBubblesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GenerateRoomTypesData = {
    body: RoomTypeInputParameters;
    path?: never;
    query?: never;
    url: '/generate/room_types';
};

export type GenerateRoomTypesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateRoomTypesError = GenerateRoomTypesErrors[keyof GenerateRoomTypesErrors];

export type GenerateRoomTypesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};